repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        exclude: ^docs/conf.py$
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.1
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, '.:src']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.610-1
    hooks:
    -   id: mypy
        exclude: ^docs/conf.py$
