repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        exclude: ^docs/conf.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.610-1
    hooks:
    -   id: mypy
        exclude: ^docs/conf.py$
